APPfoto/urls.py
from django.urls import path
from . import views

app_name = "APPfoto"

urlpatterns = [
    path(" /", views.home_view, name="home"),
    path("ricerca", views.search, name="cercaFoto"),
    path("ricerca/<str:sstring>/<str:where>", views.FotoListaRicercataView.as_view(), name="ricerca_risultati"),
    path("crea_foto/", views.CreateFotoView.as_view(), name="creafoto"),
    path("lista_foto/",views.FotoListView.as_view(), name="listafoto"),
    path("search_wrong_colour/", views.SearchWrongColourView.as_view(), name="search_wrong_colour"),
    path("situation/", views.my_situation, name="situation"),
    path("acquisto/<int:foto_id>/", views.CreaAcquisto, name="acquisto"),
    path("fotografi_lista", views.FotografiListView.as_view(), name="listafotografi")

]

foto_commerce/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('APPfoto/', include('APPfoto.urls')),
re_path(r"^$|^\/$|^home\/$",home,name="home"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("registrafotografo", FotografoCreateView.as_view(), name="registrafotografo")
]

APPfoto/models.py
from django.db import models
from django.contrib.auth.models import User  # Import the User model from Django's built-in auth

class Foto(models.Model):
    COLOUR_CHOICES = [
        ("Black", "Black"),
        ("Dark Blue", "Dark Blue"),
        ("Green", "Green"),
        ("Grey", "Grey"),
        ("Light Blue", "Light Blue"),
        ("Orange", "Orange"),
        ("Pink", "Pink"),
        ("Purple", "Purple"),
        ("Red", "Red"),
        ("White", "White"),
        ("Yellow", "Yellow"),
    ]

    name = models.CharField(max_length=50, default="No name Given")
    main_colour = models.CharField(max_length=100, choices=COLOUR_CHOICES)
    landscape = models.BooleanField()
    actual_photo = models.ImageField(upload_to='APPfoto/static')
    artist = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    price = models.DecimalField(verbose_name="prezzo", max_digits=5, decimal_places=2, default=0.00)

    def __str__(self):
        if self.landscape:
            return f"Nome foto: {self.name}, scattata da: {self.artist}, colore principale: {self.main_colour}, ed è una foto landscape."
        else:
            return f"Nome foto: {self.name}, scattata da: {self.artist}, colore principale: {self.main_colour}, ed è una foto portrait."


class Recensione(models.Model):
    foto = models.ForeignKey(Foto, on_delete=models.CASCADE, related_name="recensioni")
    utente = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recensioni_scritte")
    testo = models.CharField(max_length=250, default="Questo utente non ha lasciato una recensione scritta, "
                                                     "solo un voto.")
    voto_positivo = models.BooleanField()
    fotografo = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recensioni", null=True, blank=True)

    def scritta_da(self):
        return self.utente.username

    def testo_della_recensione(self):
        return self.testo

    def valutata(self):
        if self.voto_positivo:
            return "Valutata positivamente"
        else:
            return "Valutata negativamente"

    def save(self, *args, **kwargs):
        if self.foto:
            self.fotografo = self.foto.artist
        super(Recensione, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Recensioni"


class Acquisto(models.Model):
    MATERIALE_DI_STAMPA = [
        ("Carta Fotografica", "Carta Fotografica"),
        ("Tela", "Tela"),
        ("Carta Standard", "Carta Standard"),
        ("Lamiera Semplice", "Lamiera Semplice"),
        ("Lamiera Premium", "Lamiera Premium"),
        ("Puzzle", "Puzzle")
        ]

    DIMENSIONI = [
        ("10 x 15", "10 x 15"),
        ("12 x 18", "12 x 18"),
        ("13 x 19", "13 x 19")
    ]

    foto = models.ForeignKey(Foto, on_delete=models.CASCADE, related_name="venduti")
    acquirente = models.ForeignKey(User,on_delete=models.CASCADE, related_name="acquisti")
    materiale = models.CharField(max_length=100, choices=MATERIALE_DI_STAMPA)
    dimensioni = models.CharField(max_length=100, choices=DIMENSIONI)

APPfoto/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import *
from django.contrib.auth.models import User,Group
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class SearchForm(forms.Form):
    CHOICE_LIST = [
        ("name", "Cerca nome foto"),
        ("artist", "Cerca nome fotografo"),
        ("main_colour", "Cerca per colore principale"),
        ("landscape", "Cerca per orientamento"),
    ]

    COLOUR_CHOICES = [
        ("", "Select Color"),
        ("Black", "Black"),
        ("Dark Blue", "Dark Blue"),
        ("Green", "Green"),
        ("Grey", "Grey"),
        ("Light Blue", "Light Blue"),
        ("Orange", "Orange"),
        ("Pink", "Pink"),
        ("Purple", "Purple"),
        ("Red", "Red"),
        ("White", "White"),
        ("Yellow", "Yellow"),
    ]

    # Get users in the "Fotografi" and "Admin" groups
    fotografi_group = Group.objects.get(name='Fotografi')
    users_in_groups = User.objects.filter(groups__in=[fotografi_group])

    # Add a blank choice at the beginning of the list
    artist_choices = [("", "Select Fotografo")] + [(user.username, user.username) for user in users_in_groups]

    helper = FormHelper()
    helper.form_id = 'search_crispy_form'
    helper.form_method = "POST"
    helper.add_input(Submit('submit', 'Cerca'))

    search_string = forms.CharField(label="Cerca qualcosa", max_length=100, min_length=1, required=True)
    search_where = forms.ChoiceField(label="Ricerca per: ", required=True, choices=CHOICE_LIST)
    main_colour = forms.ChoiceField(label="Colore principale", required=False, choices=COLOUR_CHOICES)
    artist = forms.ChoiceField(label="Fotografo", required=False, choices=artist_choices)
    landscape = forms.BooleanField(label="Foto landscape", required=False)


class FotoCrispyForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_id = 'foto-crispy-form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit','Submit'))

    class Meta:
        model = Foto
        fields = ('name', 'artist', 'main_colour', 'landscape')


class CreateFotoForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = "addfoto_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Aggiungi Foto"))


    class Meta:
        model = Foto
        fields = ["name", "main_colour", "landscape", "price", "actual_photo"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["artist"].widget.attrs["readonly"] = True


class AcquistoForm(forms.ModelForm):
    class Meta:
        model = Acquisto
        fields = ["foto", "acquirente", "materiale", "dimensioni"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["acquirente"].disabled = True
        self.fields["foto"].disabled = True
        self.helper = FormHelper()
        self.helper.form_id = "acquisto_crispy_form"
        self.helper.form_method = "POST"
        self.helper.add_input(Submit("submit", "Completa l'acquisto"))

APPfoto/views.py
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import SearchForm
from django.shortcuts import render
from django.views import View
from django.db.models import Count, Exists, OuterRef, Q


def home_view(request):
    return render(request, template_name="APPfotoTempl/home.html")



class FotografiListView(ListView):
    template_name = 'APPfotoTempl/lista_fotografi.html'
    context_object_name = 'members'

    def get_queryset(self):
        fotografi_group = Group.objects.get(name='Fotografi')
        members = User.objects.filter(groups=fotografi_group).annotate(
            positive_review_count=Count('recensioni', filter=Q(recensioni__voto_positivo=True))
        )

        # Check the 'sort' query parameter and apply sorting
        sort_by = self.request.GET.get('sort')
        if sort_by == 'positive_reviews':
            members = members.order_by('-positive_review_count')
        elif sort_by == 'alphabetical':
            members = members.order_by('username')

        return members

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group_name'] = 'Fotografi'
        return context


class SearchWrongColourView(View):
    template_name = "APPfotoTempl/search_wrong_colour.html"

    def get(self, request, *args, **kwargs):
        form = SearchForm()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

        if request.method == "POST":
            form = SearchForm(request.POST)
            if form.is_valid():
                sstring = form.cleaned_data.get("search_string")
                where = form.cleaned_data.get("search_where")
                return redirect("APPfoto:ricerca_risultati", sstring, where)
            else:
                context = {'form': form}
            return render(request, self.template_name, context)


class FotoListView(ListView):
    titolo="Abbiamo trovato queste foto"
    model = Foto
    template_name = "APPfotoTempl/lista_foto.html"

def search(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            sstring = form.cleaned_data.get("search_string")
            where = form.cleaned_data.get("search_where")
            return redirect("APPfoto:ricerca_risultati", sstring, where)

    else:
        form = SearchForm()

    return render(request, "APPfotoTempl/search.html", context= {"form": form})


class FotoListaRicercataView(FotoListView):
    titolo = "risultati ricerca"
    paginate_by = 10

    def get_queryset(self):
        sstring = self.kwargs['sstring']
        where = self.kwargs['where']
        queryset = super().get_queryset()

        # Sorting options
        sort_by = self.request.GET.get('sort_by', None)

        if where == "name":
            queryset = queryset.filter(name__icontains=sstring)
        elif where == "landscape":
            queryset = queryset.filter(landscape=True)
        elif where == "main_colour":
            COLOUR_CHOICES_to_filter = ["Black","Dark Blue","Green", "Gray", "Light Blue", "Orange", "Pink",
                                        "Purple", "Red", "White", "Yellow"]
            queryset = queryset.filter(main_colour__in=COLOUR_CHOICES_to_filter)
        else:
            queryset = queryset.filter(artist__username__icontains=sstring)

        # Sort the queryset based on the sort_by parameter
        if sort_by == 'price':
            queryset = queryset.order_by('price')
        elif sort_by == 'new':
            queryset = queryset.order_by('-date_added')

        return queryset


# views.py
class CreateFotoView(LoginRequiredMixin, CreateView):
    model = Foto
    fields = ['name', 'main_colour', 'landscape', 'price', 'actual_photo']
    template_name = 'APPfotoTempl/create_entry.html'
    success_url = reverse_lazy("APPfoto:home")

    def form_valid(self, form):
        form.instance.artist = self.request.user
        return super().form_valid(form)


@login_required
def my_situation(request):
     user = get_object_or_404(User, pk=request.user.pk)
     return render(request, "APPfotoTempl/situation.html")



@login_required
def CreaAcquisto(request, foto_id):
    foto = Foto.objects.get(pk=foto_id)

    if request.method == "POST":
        form = AcquistoForm(request.POST, initial={'foto': foto, 'acquirente': request.user})

        if form.is_valid():
            acquisto = form.save(commit=False)
            acquisto.foto = foto
            acquisto.acquirente = request.user
            acquisto.save()
            return redirect('APPfoto:situation')
        else:
            messages.error(request, "Invalid form data. Please correct the errors.")
    else:
        initial_data = {'foto': foto, 'acquirente': request.user}
        form = AcquistoForm(initial=initial_data)

    # Make the acquirente field readonly and disabled
    form.fields['acquirente'].widget.attrs['readonly'] = True
    form.fields['acquirente'].widget.attrs['disabled'] = True

    context = {
        'foto': foto,
        'form': form,
    }

    return render(request, 'APPfotoTempl/acquisto.html', context)

APPfoto/templates/APPfotoTempl/acquisto.html
{% extends 'base.html' %}

{% block title %} {{ view.title }} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> {{ view.title }} </h1>
{% endblock %}

{% block content %}

<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Completa l'acquisto</button>
      </form>
    </div>
  </div>
</div>

<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/create_entry.html
{% extends 'base.html' %}

{% block title %} {{ view.title }} {% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1> {{ view.title }} </h1>
{% endblock %}

{% block content %}

<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Aggiungi Foto</button>
      </form>
    </div>
  </div>
</div>

<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/home.html
{% extends 'base.html' %}

{% block title %} Home di Super Gallery {% endblock %}

{% block header1 %}
  <h1>Home di Super Gallery</h1>
  <p>Welcome
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato, <br> Wait a minute, who are you?
    {% endif %}
  </p>
{% endblock %}

{% block content %}

<h2>Cosa si fa di bello?</h2>

<br>

<div class="list-group">
  <a href="{% url 'APPfoto:cercaFoto' %}" class="list-group-item list-group-item-info">Cerca una foto</a>
  <a href="{% url 'APPfoto:listafoto' %}" class="list-group-item list-group-item-info">Elenco delle Foto</a>
  <a href="{% url 'APPfoto:situation' %}" class="list-group-item list-group-item-info">Come siamo messi?</a>
</div>

<br>

{% if user.is_staff %}
<br>
<a href="{% url 'registrafotografo' %}" class="list-group-item list-group-item-danger">Iscrivi un fotografo alla gilda</a>
<br>
{% endif %}


{% if "Fotografi" in user.groups.all.0.name or user.is_staff %}
<br>
<!-- <a href="{ url 'gestione:situationb' %}" class="list-group-item list-group-item-warning">Situazione Biblioteca</a> -->
<a href="{% url 'APPfoto:creafoto' %}" class="list-group-item list-group-item-warning">Aggiungi una foto</a>
<!-- <a href="{ url 'gestione:creacopia' %}" class="list-group-item list-group-item-warning">Aggiungi una copia</a> -->
<br>
{% endif %}


{% endblock %}

APPfoto/templates/APPfotoTempl/lista_foto.html
{% extends 'base.html' %}

{% block title %} Elenco Foto{% endblock %}

{% load static %}

{% block header1 %}
  <h1>Elenco Foto</h1>
{% endblock %}


{% block content %}
<h2> {{ view.nome }} {{ object_list.count }} Foto </h2>
<br>

<div class="btn-group" role="group">
    <a href="?sort_by=price" class="btn btn-secondary">Sort by Price</a>
    <a href="?sort_by=new" class="btn btn-secondary">Sort by New</a>
</div>


<br>
{% if object_list %}
    {% for f in object_list %}
    <br>
    <div class="card">
        <img src="{% static f.actual_photo %}" alt="{{ f.name }}" height="500" width="500">
            <div class="card-body">
            <h5 class="card-title">{{ f.nome }}</h5>
            {% if f.landscape %}
                <p class="card-text">foto scattata da {{ f.artist_name }} in formato Landscape</p>
            {% else %}
               <p class="card-text">foto scattata da {{ f.artist_name }} in formato Portrait</p>
            {% endif %}
            Spero ti piaccia
        </div>
        <div class="card-footer">
            <a href="{% url 'APPfoto:acquisto' f.pk %}" class="btn btn-info">
                Se compra! </a>
        </div>
    </div>
    <br>
    {% endfor %}
{% else %}
    <p>No photos available. Redirecting...</p>
    <script>
         setTimeout(function() {
            window.location.href = "{% url 'APPfoto:search_wrong_colour' %}";
        }, 3000);  // Redirect after 3 seconds
    </script>
{% endif %}
<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/lista_fotografi.html
{% extends 'base.html' %}

{% block title %}Elenco Fotografi{% endblock %}

{% load static %}

{% block header1 %}
  <h1>Elenco Fotografi</h1>
{% endblock %}

{% block content %}
<h2>{{ group_name }} Members</h2>

<div>
    <a href="?sort=positive_reviews">Sort by Positive Reviews</a> |
    <a href="?sort=alphabetical">Sort Alphabetically</a>
</div>

<br>

{% if members %}
    <ul>
        {% for member in members %}
        <li>
            <h3>{{ member.username }}</h3>
            <p>Positive Reviews: {{ member.positive_review_count }}</p>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No members in the "fotografi" group.</p>
{% endif %}
<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/search.html
{% extends 'base.html' %}

{% block title %} Cerca tra le foto{% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



{% block header1 %}
  <h1>Cerca tra le foto</h1>
{% endblock %}

{% block content %}

<h2> Cerca tra le foto </h2>

<br>

{% if redirect_param %}

    <br>
    Sei stato rimandato a questa pagina perchè la ricerca non ha prodotto risultati <br>

    Ti ricordo che i colori disponibili sono: <br>
    Black,Dark Blue, Green, Gray, Light Blue, Orange, Pink, Purple, Red, White e Yellow.


<br>

{% else %}
    Sei in modalità di ricerca normale.
    <div class="d-flex justify-content-center">
        {% crispy form %}
    </div>
{% endif %}

<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/search_wrong_colour.html
{% extends 'base.html' %}

{% block title %} Cerca tra le foto{% endblock %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
  <h1>Cerca tra le foto</h1>
{% endblock %}

{% block content %}

<h2> Cerca tra le foto </h2>

<br>

{% if form.errors %}
<div class="alert alert-danger" style="background-color: rgba(255, 0, 0, 0.2);">
  <strong>Error:</strong> HAVE YOU EVER KILLED WITH ALL THE COLOURS OF THE WIND?.
</div>
{% endif %}

<br>

<div class="d-flex justify-content-center">
  {% crispy form %}
</div>
<br>
    Sei stato rimandato a questa pagina perchè la ricerca non ha prodotto risultati <br>

    Ti ricordo che i colori disponibili sono: <br>
    Black,Dark Blue, Green, Gray, Light Blue, Orange, Pink, Purple, Red, White e Yellow.


<br>

{% endblock %}

APPfoto/templates/APPfotoTempl/situation.html
{% extends 'base.html' %}

{% block title %} Home di {{ user.username }} {% endblock %}

{% block header1 %}
  <h1>Home di {{ user.username }} </h1>
  <p>Benvenuto
    {% if user.is_authenticated %}
     {{ user.username }}
    {% else %}
    Utente non registrato
        <br>
        Wait a minute, who are you?
    {% endif %}
  </p>
{% endblock %}

{% block content %}
  <h2> Vediamo se ci azzecco, la sfera di cristallo dice che hai comprato: </h2>

  <br>

  <!-- Iterate over Acquisto objects for the current user -->
  {% for acquisto in user.acquisti.all %}
    <div class="card">
      <div class="card-header">
         Acquisto con id {{ acquisto.pk }}
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ acquisto.foto.name }}</h5>
        <p class="card-text">Una foto di {{ acquisto.foto.artist.username }} </p>
        <p class="card-text">Materiale: {{ acquisto.get_materiale_display }}</p>
        <p class="card-text">Dimensioni: {{ acquisto.get_dimensioni_display }}</p>

        <!-- Add a link to manage the acquisto, replace 'your_url_name' with your actual URL name -->
        <!--
        <a href="{ url 'your_url_name' acquisto.pk %}" class="btn btn-info"> Gestisci Acquisto </a>
        -->

      </div>
    </div>
    <br>
  {% endfor %}

  <br>

{% endblock %}